/* ══════════════════════════════════════════════════════════════
   BLOG DATA — KiriTour Madagascar
   Articles SEO-optimized — internal links → /tours
══════════════════════════════════════════════════════════════ */

export const posts = [
  {
    slug: "best-time-visit-avenue-baobabs-madagascar",
    title: "Best Time to Visit the Avenue of the Baobabs (2026 Guide)",
    excerpt: "Planning to see Madagascar's most iconic sunset? Here's exactly when to visit the Avenue of the Baobabs for the best light, weather and fewest crowds.",
    cover: "https://i.ibb.co/4ZMwFVFh/IMG-20251030-WA0008.jpg",
    date: "2026-06-01",
    readTime: "6 min",
    category: "Travel Guide",
    keywords: "when to visit baobabs, avenue of the baobabs best time, morondava weather, madagascar dry season, baobabs sunset",
    relatedTour: "avenue-baobabs-betania-kimony-day-tour-morondava",
    relatedTourLabel: "Avenue of the Baobabs Day Tour",
    content: [
      { type: "p", text: "The Avenue of the Baobabs near Morondava is one of Madagascar's most photographed places — a row of ancient, towering baobab trees that glow gold at sunset. But timing your visit matters enormously. The right month and time of day can transform an ordinary stop into an unforgettable experience." },
      { type: "h2", text: "The Best Months: April to November (Dry Season)" },
      { type: "p", text: "The dry season, from April to November, is the best time to visit the Avenue of the Baobabs. Roads to Morondava and beyond are passable, skies are clear, and the famous baobab silhouettes stand out crisply against orange sunsets. The peak window of July to September offers the most reliable weather, though it is also the busiest." },
      { type: "p", text: "From December to March, the rainy season makes the dirt roads to the baobabs — and especially to Tsingy and Kirindy — difficult or impossible. Some tracks become completely impassable. If you can, plan your western Madagascar trip in the dry months." },
      { type: "h2", text: "Best Time of Day: Sunset (and Sunrise)" },
      { type: "p", text: "The Avenue earns its fame at sunset, roughly between 4:30 PM and 6:00 PM depending on the season. The low sun turns the baobabs into dramatic black silhouettes against a burning sky. Arrive at least 45 minutes early to find your spot and watch the light change." },
      { type: "p", text: "Sunrise is the quieter alternative — fewer people, soft pink light and a peaceful atmosphere. Many travellers do both: sunrise one day, sunset another." },
      { type: "tip", text: "Golden hour fills up fast in peak season. A local guide knows the best vantage points away from the crowds and the exact light timing for that month." },
      { type: "h2", text: "How Long Do You Need?" },
      { type: "p", text: "The baobabs themselves take an hour or two at sunset. But the Avenue pairs perfectly with nearby Kirindy Forest (fossa and lemurs) and the Tsingy de Bemaraha UNESCO site. A 2 to 4 day western circuit lets you combine all the highlights of the Menabe region in one trip." },
      { type: "h2", text: "Getting There" },
      { type: "p", text: "The Avenue is about 20 km north of Morondava on the road to Belo-sur-Tsiribihina — around 30 to 45 minutes by 4x4. A private guided tour handles transport, timing and photography stops so you arrive exactly when the light is best." },
    ],
  },
  {
    slug: "tsingy-de-bemaraha-travel-guide",
    title: "Tsingy de Bemaraha: Complete Travel Guide 2026",
    excerpt: "Everything you need to know to visit Tsingy de Bemaraha — Madagascar's UNESCO stone forest: how to get there, what to expect, difficulty and the best tours.",
    cover: "https://i.ibb.co/zhTgMVW2/IMG-20250915-211514.jpg",
    date: "2026-06-03",
    readTime: "8 min",
    category: "Travel Guide",
    keywords: "tsingy de bemaraha, how to visit tsingy, unesco madagascar, bekopaka, grand tsingy, tsingy tour",
    relatedTour: "tsingy-de-bemaraha-4-day-unesco-kirindy-baobabs",
    relatedTourLabel: "Tsingy de Bemaraha 4-Day Tour",
    content: [
      { type: "p", text: "Tsingy de Bemaraha is one of the most extraordinary landscapes on Earth — a vast forest of razor-sharp limestone pinnacles that rise like a stone cathedral. A UNESCO World Heritage Site, it sits in western Madagascar and rewards the adventurous traveller with hikes across suspension bridges, through caves and up to breathtaking viewpoints." },
      { type: "h2", text: "What Are the Tsingy?" },
      { type: "p", text: "The word tsingy means \"where one cannot walk barefoot\" in Malagasy — a fitting name for the needle-like limestone formations carved by millennia of rain. The park is divided into the Grand Tsingy (taller, more technical) and the Petit Tsingy (smaller, more accessible), each offering different trails and viewpoints." },
      { type: "h2", text: "How to Get to Tsingy de Bemaraha" },
      { type: "p", text: "The gateway town is Bekopaka, reached by 4x4 from Morondava via Belo-sur-Tsiribihina, with two river ferry crossings along the way. The journey takes most of a day on rough dirt roads and is only possible in the dry season, roughly April to November." },
      { type: "tip", text: "Because of the ferry crossings and remote roads, a guided 4x4 tour is by far the easiest and safest way to reach Bekopaka. Going independently is slow and risky." },
      { type: "h2", text: "How Difficult Is the Hike?" },
      { type: "p", text: "The Grand Tsingy circuit is physically demanding — you'll use fixed harnesses (via ferrata), climb ladders and squeeze through narrow passages. A reasonable level of fitness and no fear of heights helps. The Petit Tsingy is gentler and suits most visitors. Guides provide and fit all safety equipment." },
      { type: "h2", text: "What Wildlife Will You See?" },
      { type: "p", text: "Tsingy is home to endemic lemurs like the Decken's sifaka and red-fronted brown lemur, plus chameleons, birds and unique plants growing among the stone. The dramatic scenery is the star, but the wildlife makes it special." },
      { type: "h2", text: "Best Tours: Combine with Baobabs and Kirindy" },
      { type: "p", text: "Most travellers visit Tsingy as part of a 3 to 4 day western circuit that also includes the Avenue of the Baobabs and Kirindy Forest. This makes the long drive worthwhile and packs in Madagascar's western highlights — stone forest, wildlife and iconic baobabs — in a single trip." },
    ],
  },
  {
    slug: "kirindy-forest-fossa-lemurs-guide",
    title: "How to See the Fossa & Lemurs in Kirindy Forest",
    excerpt: "Kirindy Forest is the best place in Madagascar to spot the elusive fossa, plus lemurs and nocturnal wildlife. Here's how to maximise your sightings.",
    cover: "https://i.ibb.co/C5CXsY8M/IMG-20251030-WA0106.jpg",
    date: "2026-06-05",
    readTime: "6 min",
    category: "Wildlife",
    keywords: "kirindy forest, fossa madagascar, see fossa, lemurs morondava, night walk madagascar, kirindy wildlife",
    relatedTour: "kirindy-forest-fossa-lemurs-2-day-safari",
    relatedTourLabel: "Kirindy Forest 2-Day Safari",
    content: [
      { type: "p", text: "Kirindy Forest is one of Madagascar's wildlife jewels — a dry deciduous forest near Morondava that offers the best chance in the country to see the fossa, the island's largest predator. Combined with several lemur species and rich nocturnal life, it's a must for wildlife lovers visiting the west." },
      { type: "h2", text: "The Fossa: Madagascar's Apex Predator" },
      { type: "p", text: "The fossa is a cat-like carnivore found only in Madagascar and the island's top predator. Kirindy is famous as the most reliable place to see one, especially around the research camp where they are sometimes spotted during the day. Patience and an experienced guide dramatically improve your chances." },
      { type: "h2", text: "When Is the Best Time to Visit?" },
      { type: "p", text: "The dry season (April to November) is best for both access and wildlife. Fossa sightings peak during their mating season, roughly October to December, when the animals are more active and visible. The roads are also passable in these months." },
      { type: "tip", text: "Fossa are unpredictable — no guide can guarantee a sighting. Spending a night in or near Kirindy, with both dusk and dawn walks, gives you the best odds." },
      { type: "h2", text: "Lemurs and Night Walks" },
      { type: "p", text: "Kirindy hosts several lemur species, including Verreaux's sifaka and the red-fronted brown lemur by day. But the night walk is the real highlight: with a headlamp and guide, you can spot the tiny mouse lemur (one of the world's smallest primates), chameleons, geckos and nocturnal birds." },
      { type: "h2", text: "How to Visit Kirindy" },
      { type: "p", text: "Kirindy is about 60 km northeast of Morondava, roughly 2 hours by 4x4, often combined with a sunset stop at the Avenue of the Baobabs on the way. A 1-day trip is possible, but staying overnight for a night walk and an early morning walk maximises wildlife sightings." },
    ],
  },
  {
    slug: "tsiribihina-river-descent-complete-guide",
    title: "Tsiribihina River Descent: Complete Guide 2026",
    excerpt: "A 2-3 day pirogue descent down the Tsiribihina is one of Madagascar's great adventures. Here's what to expect, when to go and how to prepare.",
    cover: "https://i.ibb.co/Y774QKWz/IMG-20260224-WA0044.jpg",
    date: "2026-06-07",
    readTime: "7 min",
    category: "Travel Guide",
    keywords: "tsiribihina river, pirogue descent madagascar, tsiribihina tour, miandrivazo, river camping madagascar, sakalava villages",
    relatedTour: "tsiribihina-river-3-day-pirogue-descent-madagascar",
    relatedTourLabel: "Tsiribihina River 3-Day Descent",
    content: [
      { type: "p", text: "Drifting down the Tsiribihina River in a traditional wooden pirogue is one of the most peaceful and authentic adventures in western Madagascar. Over two or three days you pass red cliffs, sacred Sakalava villages, waterfalls and untouched riverine forest, camping on wild sandbanks under a sky full of stars." },
      { type: "h2", text: "Where Does the Descent Start?" },
      { type: "p", text: "Most descents begin in Miandrivazo, a town reached by road from Antananarivo or Morondava. From there you board the pirogue and float gently downstream toward Belo-sur-Tsiribihina, where the river journey ends and a 4x4 continues to Kirindy or the baobabs." },
      { type: "h2", text: "How Many Days Do You Need?" },
      { type: "p", text: "The classic descent is three days and two nights, giving a relaxed pace with time for swimming, village visits and birdwatching. A faster two-day version is possible, while longer trips combine the river with Tsingy de Bemaraha and Kirindy Forest for a full western circuit." },
      { type: "h2", text: "What Is Daily Life Like on the River?" },
      { type: "p", text: "Days are slow and restful. Your crew paddles and steers while you relax, swim in calm pools and watch kingfishers and herons along the banks. Evenings are spent at camp on a sandbank, with simple Malagasy meals cooked over a fire and a sky bright with stars far from any city light." },
      { type: "tip", text: "Bring sun protection, a hat, a dry bag for electronics and a light layer for cool evenings. Your guide handles tents, cooking and all river logistics." },
      { type: "h2", text: "Best Time to Go" },
      { type: "p", text: "The dry season from April to November is ideal, with comfortable water levels and pleasant weather. Avoid the rainy season (December to March), when water levels and road access become unpredictable." },
      { type: "h2", text: "Combining the River with Tsingy and Baobabs" },
      { type: "p", text: "The Tsiribihina descent pairs naturally with the highlights of the Menabe region. Many travellers continue from Belo to Kirindy Forest for fossa and lemurs, then finish at the Avenue of the Baobabs at sunset — a perfect western Madagascar loop." },
    ],
  },
  {
    slug: "madagascar-itinerary-from-morondava",
    title: "Madagascar Itinerary: How to Plan Your Trip from Morondava",
    excerpt: "Morondava is the gateway to western Madagascar's icons. Here's how to plan a 3, 5 or 7+ day itinerary covering baobabs, Tsingy, Kirindy and the river.",
    cover: "https://i.ibb.co/7JmwLVGv/20250803-092258.jpg",
    date: "2026-06-09",
    readTime: "8 min",
    category: "Travel Guide",
    keywords: "madagascar itinerary, morondava travel, western madagascar trip, how many days madagascar, menabe circuit, madagascar trip planning",
    relatedTour: "western-madagascar-5-day-circuit-baobabs-kirindy",
    relatedTourLabel: "Western Madagascar 5-Day Circuit",
    content: [
      { type: "p", text: "Morondava, on Madagascar's west coast, is the perfect base for exploring the wonders of the Menabe region — the Avenue of the Baobabs, Kirindy Forest, Tsingy de Bemaraha and the Tsiribihina River. How you combine them depends on how many days you have. Here's how to plan." },
      { type: "h2", text: "Short Trip: 1-2 Days" },
      { type: "p", text: "With limited time, focus on the icons closest to Morondava. A day tour to the Avenue of the Baobabs at sunset, combined with the nearby Kimony beach and Betania fishing village, gives a strong taste of the region. Add a day trip to Kirindy Forest for your first lemurs and a chance at spotting a fossa." },
      { type: "h2", text: "Classic Trip: 3-4 Days" },
      { type: "p", text: "Three to four days is enough to reach Tsingy de Bemaraha, the UNESCO stone forest. A typical loop drives from Morondava to Bekopaka (with a baobabs stop), explores the Grand and Petit Tsingy, then returns via Kirindy Forest for wildlife and a final baobabs sunset." },
      { type: "h2", text: "Complete Trip: 5-7 Days" },
      { type: "p", text: "With a week, you can add the Tsiribihina River descent to the circuit, combining a peaceful pirogue journey with the Tsingy, Kirindy and baobabs. This is the most complete western Madagascar experience, blending river, stone forest, wildlife and iconic landscapes." },
      { type: "tip", text: "Western Madagascar's roads are rough and remote, with river ferry crossings. A private 4x4 with a local guide saves time, handles logistics and is far safer than going independently." },
      { type: "h2", text: "When to Visit" },
      { type: "p", text: "Plan your trip in the dry season, April to November. The roads to Tsingy and Kirindy are only reliably passable in these months, and the weather is best for the baobabs at sunset. The rainy season can cut off access to the interior entirely." },
      { type: "h2", text: "How to Get to Morondava" },
      { type: "p", text: "Morondava has a small airport with flights from Antananarivo, or you can travel overland. Once you arrive, a guided tour takes care of all transport and accommodation so you can focus on the experience rather than the logistics." },
    ],
  },
  {
    slug: "what-to-pack-madagascar-safari",
    title: "What to Pack for a Madagascar Safari & Tour",
    excerpt: "Heading to Madagascar's baobabs, Tsingy and forests? This practical packing list covers clothing, gear and essentials for a comfortable western Madagascar trip.",
    cover: "https://i.ibb.co/CsJNYXX1/IMG-20260224-WA0050.jpg",
    date: "2026-06-11",
    readTime: "6 min",
    category: "Travel Tips",
    keywords: "madagascar packing list, what to pack madagascar, madagascar safari gear, madagascar travel essentials, tsingy hiking gear",
    relatedTour: "tsingy-de-bemaraha-4-day-unesco-kirindy-baobabs",
    relatedTourLabel: "Tsingy de Bemaraha 4-Day Tour",
    content: [
      { type: "p", text: "Packing well makes a big difference on a western Madagascar trip, where you'll move between hot baobab plains, sharp Tsingy limestone, humid forests and wild river camps. Here's a practical list of what to bring for comfort and safety." },
      { type: "h2", text: "Clothing" },
      { type: "p", text: "Pack light, breathable clothes in neutral colours: quick-dry shirts, trousers that protect against sun and scratches, and shorts for hot days. Bring a light fleece or jacket for cool mornings and evenings, especially in the forests and on the river. A hat and a buff or scarf protect against sun and dust." },
      { type: "h2", text: "Footwear" },
      { type: "p", text: "Sturdy closed hiking shoes with good grip are essential, particularly for the Tsingy where you walk across sharp limestone. Bring sandals or flip-flops for camp and river crossings." },
      { type: "h2", text: "Sun & Insect Protection" },
      { type: "p", text: "The western sun is strong. Pack high-SPF sunscreen, lip balm, sunglasses and insect repellent. Long sleeves in the evening help against mosquitoes, especially near the river and forests." },
      { type: "tip", text: "A headlamp is essential for night walks in Kirindy and for camp on the Tsiribihina. Bring spare batteries — there's little or no electricity in remote areas." },
      { type: "h2", text: "Gear & Essentials" },
      { type: "p", text: "Useful items include a refillable water bottle, a dry bag to protect electronics on the river, a power bank (charging is limited in remote areas), a small first-aid kit with any personal medication, and a camera with extra memory and batteries for the wildlife and landscapes." },
      { type: "h2", text: "Documents & Money" },
      { type: "p", text: "Carry your passport, travel insurance details and some cash in small denominations, as card payments are rare outside the cities. Keep digital and paper copies of important documents in case of loss." },
      { type: "h2", text: "Travel Light, Travel Smart" },
      { type: "p", text: "A medium backpack or soft duffel works best for 4x4 travel and pirogue trips, where space is limited. Your guide can advise on exactly what you'll need for your chosen tour, so you only carry what's useful." },
    ],
  },
];

export const POST_BY_SLUG = Object.fromEntries(posts.map((p) => [p.slug, p]));